apiVersion: v1
kind: Service
metadata:
  name: simple-go-server
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: http
  selector:
    app: simple-go-server
  type: ClusterIP
